import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "./components/Navbar";
import BootstrapClient from "./components/BootstrapClient";
import 'react-toastify/dist/ReactToastify.css';
import { ReactQueryClientProvider } from "./components/ReactQueryClient";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Loja WA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryClientProvider>
          <Navbar />
          <ToastContainer />
        {children}
        <BootstrapClient />
      </ReactQueryClientProvider>
      </body>
    </html>
  );
}
